services:
  - type: web
    name: medibot
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: medical-chatbot
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
